name: Dump

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 5 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      - run: npm install
      - uses: mujo-code/puppeteer-headful@master
        with:
          args: CI=true node . ${{ secrets.VLOGIN }} ${{ secrets.VPASSWORD }}
        
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          SSH: true
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: output

